# IF SRVY_YR > 2007 
# THEN DO;
# OTHERPUB = OTHPUB;
# END;
# IF SRVY_YR > 2003 
# THEN DO
# CHIP = SCHIP;
# END;
# IF SRVY_YR < 2004 
# THEN DO;
# *** MEDICAID/PUBLIC ASSISTANCE ;
# *** MCAID=1 IF YES, HAS MEDICAID OR PUBLIC ASSISTANCE ;
# *** MCAID=0 IF NO, DOES NOT HAVE MEDICAID OR PUBLIC ASSISTANCE OR 
# UNKNOWN ON SUCH COVERAGE ;
# IF MEDICAID IN (1,2) OR OTHERPUB IN (1) OR CHIP IN (1)
# THEN MCAID = 1;
# ELSE IF (MEDICAID > 3 OR MEDICAID <= 0) OR (CHIP > 2 OR CHIP <= 0) OR 
# (OTHERPUB > 2 OR OTHERPUB <= 0) 
# THEN MCAID = 9;
# ELSE MCAID = 2;
# END;
# ELSE IF SRVY_YR > 2003 
# THEN DO;
# *** MEDICAID/PUBLIC ASSISTANCE;
# *** MCAID = 1 IF YES, HAS MEDICAID OR PUBLIC ASSISTANCE ;
# *** MCAID = 0 IF NO, DOES NOT HAVE MEDICAID OR PUBLIC ASSISTANCE
# OR UNKNOWN ON SUCH COVERAGE ;
# IF MEDICAID IN (1,2) OR OTHERPUB IN (1,2) OR CHIP IN (1,2)
# THEN MCAID = 1;
# ELSE IF (MEDICAID > 3 OR MEDICAID <= 0) OR (CHIP > 3 OR CHIP <= 0) OR (OTHERPUB > 3 OR OTHERPUB <= 0) 
# THEN MCAID = 9;
# ELSE MCAID = 2;
# END;
# *DICHOTOMIZED PRIVATE COVERAGE;
# IF PRIVATE IN (1 2) 
# THEN PRICOV = 1;
# ELSE IF PRIVATE = 3 
# THEN PRICOV = 2;
# ELSE IF PRIVATE > 3 
# THEN PRICOV = 3;
# *THIS CODE IS A HIERARCHY, COULD ALSO USE THE OVERLAPPING CODE FROM HUS;
# IF NOTCOV = 1 AND PRICOV = 2 AND MCAID = 2 
# THEN INSTYPE = 1; *UNINSURED, NOT PRIVATE, NOT MEDICAID;
# IF NOTCOV = 2 AND PRICOV = 2 AND MCAID = 1 
# THEN INSTYPE = 2; *MEDICAID (INCL OTHPUB AND CHIP), NOT PRIVATE, NOT UNINSURED;
# IF NOTCOV = 2 AND PRICOV = 1 
# THEN INSTYPE = 3; *PRIVATE, NOT MEDICAID, NOT UNINSURED;
# IF NOTCOV = 2 AND PRICOV = 2 AND MCAID = 2 
# THEN INSTYPE = 4; *OTHER INSURED -- ABOUT 10%;

# stacked 2000-2015 data with variables
# linking variables srvy_yr srvy_yr, hhx, fmx, fpx
# from personsx:
#   othpub, othpub, chip, schip, medicaid, private, notcov
# outcome variable from samadult: ahernoy2

# mcaid = case_when(
#   srvy_yr %in% 2000:2003 & (medicaid %in% 1:2 | otherpub == 1 | chip == 1) ~ 1
#   srvy_yr %in% 2000:2003 & (medicaid > 3 | medicaid <= 0) OR (CHIP > 2 OR CHIP <= 0) OR 
# (OTHERPUB > 2 OR OTHERPUB <= 0) 
# THEN MCAID = 9;
# )


# srvy_yr %in% 2004:2015

